---
# tasks file for docker
- name: Install Docker Dependecies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update-cache: true
- name: Create Keyrings Directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
- name: Add Docker's Official GPG Key
  apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present
- name: Add The Repository To Apt Sources
  apt_repository:
    repo: "{{ docker_repository_url }}"
    state: present
- name: Install Docker
  apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: "{{ docker_version }}"
    update-cache: true