version: '3.7'

services:
  django:
    container_name: django-container
    image: django-locallibrary-tutorial
    volumes:
      - static:/static
    build: ./django-locallibrary-tutorial
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static:
